# Generated by Django 5.1.1 on 2025-08-20 20:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=2, null=True, verbose_name='Level')),
                ('instruction', models.TextField(blank=True, null=True, verbose_name='Insturction')),
                ('timing', models.IntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=60, null=True)),
                ('user_e_mail', models.EmailField(max_length=254)),
                ('user_message', models.TextField(blank=True, null=True)),
                ('date_time_message', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('english_level', models.CharField(max_length=2, null=True)),
                ('time_consumed', models.SmallIntegerField(default=0)),
                ('topic_score', models.TextField(blank=True, null=True)),
                ('total_score', models.SmallIntegerField(default=0)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GrammarTopics',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grammar_name', models.TextField(blank=True, null=True, verbose_name='Grammar section')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.levels', verbose_name='topics')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Questions')),
                ('grammar_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.grammartopics', verbose_name='Grammar section')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='Answers')),
                ('right_wrong', models.BooleanField()),
                ('worth', models.SmallIntegerField()),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='content.questions', verbose_name='Question')),
            ],
        ),
    ]
