# Generated by Django 5.1.1 on 2025-08-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_prioritymap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriorityMap',
        ),
        migrations.AddField(
            model_name='grammartopics',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
